### PR TITLE
FIX add quay.io part 1 jenkins-slave-npm

### PR DESCRIPTION
**Pull request by NissesSenap**
Without quay.io defined you get the following error: 
"Error from server (NotFound): imagestreams.image.openshift.io \"jenkins-slave-npm\"

When running: ansible-playbook apply.yml -e target=tools \
 -i inventory/ \
 -e "filter_tags=jenkins"

### CODE REVIEW

**Comment by springdo** [comment]
Hi Edvin, Thanks for raising this PR.  I spoke with Dmytri and I think this issue is something slightly different as to what was originally assumed. The  `jenkins-slave-npm` we use in the enablement is a custom created image and so using the `quay.io/openshift/jenkins-slave-npm` one will not work for later lessons. 

However, I do like your approach and it would make sure we don't forget to tag the image into the openshift namepsace in the future ..... so tomorrow when in class can you test again but by pulling the image from `quay.io/rht-labs/enablement-npm:latest` for use as `jenkins-slave-npm:latest` in your project. Thanks!

**Comment by NissesSenap** [comment]
Hi @springdo , thanks for a quick reply.

Okay good to know, I'm trying to get a feeling for the labs repos, can you point my where you do this tagging?
I gave it a try now and quay.io/rht-labs/enablement-npm:latest worked. Do you want me to update the PR or will you do it in another PR?

Regards Edvin

**Comment by springdo** [comment]
Happy for you to update it!

**Comment by NissesSenap** [comment]
Done :)

**Pull request merged**
