### PR TITLE
Updated exercise 'inventory' to use v2.0.0 'action'

### PR DESCRIPTION
**Pull request by oybed**
Related to PR https://github.com/rht-labs/enablement-ci-cd/pull/14 ... to move to `openshift-applier` newest release `v2.0.0`. 

@springdo not sure if I caught everywhere where this change needs to be made, so please let me know if there anywhere else (in other branches) that needs to be updated as well.

### CODE REVIEW

**Comment by mtakane** [comment]
@springdo bump! or happy to see if someone else would like to review this as well? @syvanen ?

**Comment by syvanen** [comment]
But as this is tied to the https://github.com/rht-labs/enablement-ci-cd -repo, shall we first update all the branches before changing the document?

**Comment by oybed** [comment]
@syvanen agreed that there may be some additional work needed for this ... we'd have to check it out.

**Comment by oybed** [comment]
Too late - closing

**Pull request closed without merging**
