### PR TITLE
Feature/readme

### PR DESCRIPTION
**Pull request by misanche**
Updated Readme with NodeJS prerequisites

### CODE REVIEW

**Comment by jtudelag** [comment]
LGTM!

**Comment by rmarting** [comment]
Is there some ETA to review and approve this PR? We are preparing an enablement and it should be nice to have this content added.

**Comment by jtudelag** [comment]
@misanche are the package.json versions still appropiate?

**Comment by misanche** [comment]
Hi @jtudelag, express already has the latest version, socket.io has been updated to 3.1.x but it's a mayor version and should be tested. I would say that it's better to use the PR ones that the current ones.

**Comment by jtudelag** [comment]
ok then, merging it!

**Pull request merged**
