### PR TITLE
Create lego TDD exercise

### PR DESCRIPTION
**Pull request by springdo**
Creating a Lego TDD exercise to boost the testing section with some hands on experience with the practice but removing the techie stuff.

FYI  -  @mtakane @oybed @theisey @maryprovinciatto @tdbeattie

### CODE REVIEW

**Comment by oybed** [comment]
+ @eformat 

I think this is a good start. Will think about it some more and provide additional comments.

**Comment by springdo** [comment]
Bump - this exercise has been tried out twice now on the DO500 and seems to be a success. Defo lessons the cognitive load on the slightly less technical attendees and speeds up time spend in techie exercise land

**Comment by oybed** [comment]
@springdo when we get a chance, I think we want to see an overview/demo of how this was executed for DO500. Mind taking the lead on setting something up?

@mtakane @mcanoy @jacobsee @tylerauerbeck FYI

**Comment by springdo** [comment]
Hey @oybed  - yeah that's cool, I can show you how we did it. Got some nice pictures to update the exercise with too! The notes are in the slides too and the upstream link to where we butchered content was taken from too is there if you wanna take a look before hand

**Comment by oybed** [comment]
Related to issue #319

**Pull request merged**
